[package]
name = "just_png"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.60"
clap = {version="3.2.16", features=["derive"]}
crc = "3.0.0"
